#!/bin/bash

if [[ -f `pwd`/sharedfuncs ]]; then
  source sharedfuncs
else
  echo "missing file: sharedfuncs"
  exit 1
fi

###################
# developer tools #
###################

package_install "nodejs npm"
package_install "jre8-openjdk jdk8-openjdk openjdk8-doc"
aur_package_install "sublime-text-dev"

# postgresql

# mysql

# mongodb
