#!/bin/bash

check_connection(){ #{{{
  XPINGS=$(( $XPINGS + 1 ))
  connection_test() {
    ping -q -w 1 -c 1 `ip r | grep default | awk 'NR==1 {print $3}'` &> /dev/null && return 1 || return 0
  }
  WIRED_DEV=`ip link | grep "eno\|enp" | awk '{print $2}'| sed 's/://' | sed '1!d'`
  WIRELESS_DEV=`ip link | grep wlp | awk '{print $2}'| sed 's/://' | sed '1!d'`
  if connection_test; then
    echo "ERROR! Connection not Found."
    echo "Network Setup"
    local _connection_opts=("Wired Automatic" "Wired Manual" "Wireless" "Configure Proxy" "Skip")
    PS3="$prompt1"
    select CONNECTION_TYPE in "${_connection_opts[@]}"; do
      case "$REPLY" in
        1)
          sudo systemctl start dhcpcd@${WIRED_DEV}.service
          break
          ;;
        2)
          sudo systemctl stop dhcpcd@${WIRED_DEV}.service
          sudo ip link set ${WIRED_DEV} down
          read -p "IP Address: " IP_ADDR
          read -p "Submask: " SUBMASK
          read -p "Gateway: " GATEWAY        
          sudo ip addr add ${IP_ADDR}/${SUBMASK} dev ${WIRED_DEV}
          sudo ip route add default via ${GATEWAY}
          sudo ip link set ${WIRED_DEV} up
          # $EDITOR /etc/resolv.conf
          break
          ;;
        3)
          sudo ip link set ${WIRELESS_DEV} up
          sudo wifi-menu ${WIRELESS_DEV}
          break
          ;;
        4)
          read -p "Enter your proxy e.g. protocol://adress:port: " OPTION
          export http_proxy=$OPTION
          export https_proxy=$OPTION
          export ftp_proxy=$OPTION
          echo "proxy = $OPTION" > ~/.curlrc
          break
          ;;
        5)
          break
          ;;
        *)
          invalid_option
          ;;
      esac
    done
    if [[ $XPINGS -gt 2 ]]; then
      echo "Can't establish connection. exiting..."
      exit 1
    fi
    [[ $REPLY -ne 5 ]] && check_connection
  else
    sudo ip link set ${WIRED_DEV} down
    sudo ip link set ${WIRED_DEV} up    
  fi
} #}}}

check_connection