#!/bin/bash

aur_pkg_install(){

  PWD_DIR=`pwd`

  su - ${USER_NAME} -c "sudo -v"

  for PKG in $1; do
    curl -o ${PKG}.tar.gz https://aur.archlinux.org/cgit/aur.git/snapshot/${PKG}.tar.gz
    tar zxvf ${PKG}.tar.gz
    rm ${PKG}.tar.gz
    cd ${PKG}
    makepkg -csi --noconfirm
    pacman -U ${PKG}.tar.xz
    cd ${PWD_DIR}
  done
}

#######
# aur #
#######

# aur_package_install "libgee06"
# aur_package_install "gnome-encfs-manager" # libgee06 as dependency
aur_pkg_install "dropbox"
aur_pkg_install "sublime-text-dev"
aur_pkg_install "atom-editor"
# aur_package_install "visual-studio-code"